/**
 * 职业关系树 这个东西没有在程序里找到 只能人工输入 min表示这个职业所需的最少技能点
 * ms是标志位,可以是任何值,判断的时候只测试是否存在这个属性,存在就认为是二转职业 mainstay。 prev里是前一职业名称
 * 医生这个职业在游戏里叫医师，但从数据文件里提取出来的就是医生，这里改成医生是为了跟生成的数据吻合
 */
var profRela = [
    // 新职业
    {
        name: "拳师",
        min: 20,
        ms: 1,
        prev: "菜鸟"
    }, {
        name: "钧天",
        prev: "拳师"
    }, {
        name: "琴师",
        min: 20,
        ms: 1,
        prev: "菜鸟"
    }, {
        name: "绝弦",
        prev: "琴师"
    }, {
        name: "秀才",
        min: 20,
        ms: 1,
        prev: "菜鸟"
    }, {
        name: "书生",
        prev: "秀才"
    }, {
        name: "百卉",
        min: 20,
        ms: 1,
        prev: "菜鸟"
    }, {
        name: "花雨",
        prev: "百卉"
    }, {
        name: "玄策",
        min: 20,
        ms: 1,
        prev: "菜鸟"
    }, {
        name: "鬼谋",
        prev: "玄策"
    },
    // 人族
    {
        name: "菜鸟",
        min: 6
    }, {
        name: "游侠",
        min: 13,
        prev: "菜鸟"
    }, {
        name: "枪豪",
        min: 20,
        prev: "游侠",
        ms: 1
    }, {
        name: "刀君",
        prev: "枪豪"
    }, {
        name: "戟神",
        prev: "枪豪"
    }, {
        name: "修罗",
        prev: "枪豪"
    }, {
        name: "剑客",
        min: 20,
        prev: "游侠",
        ms: 1
    }, {
        name: "剑圣",
        prev: "剑客"
    }, {
        name: "天剑",
        prev: "剑客"
    }, {
        name: "邪皇",
        prev: "剑客"
    }, {
        name: "散人",
        min: 13,
        prev: "菜鸟"
    }, {
        name: "医生",
        min: 20,
        prev: "散人",
        ms: 1
    }, {
        name: "神算",
        prev: "医生"
    }, {
        name: "医仙",
        prev: "医生"
    }, {
        name: "明王",
        prev: "医生"
    }, {
        name: "术士",
        min: 20,
        prev: "散人",
        ms: 1

    }, {
        name: "魔尊",
        prev: "术士"
    }, {
        name: "天师",
        prev: "术士"
    }, {
        name: "蛊王",
        prev: "术士"
    },
    // 魔族
    {
        name: "魔灵",
        min: 6
    }, {
        name: "战灵",
        min: 13,
        prev: "魔灵"
    }, {
        name: "斗魂",
        min: 20,
        prev: "战灵",
        ms: 1
    }, {
        name: "隐杀",
        min: 20,
        prev: "战灵",
        ms: 1
    }, {
        name: "御魄",
        min: 20,
        prev: "战灵",
        ms: 1
    }, {
        name: "鬼斩",
        prev: "斗魂",
        isThree: 1
    }, {
        name: "烈刃",
        prev: "斗魂",
        isThree: 1
    }, {
        name: "潜行",
        prev: "隐杀",
        isThree: 1
    }, {
        name: "暗影",
        prev: "隐杀",
        isThree: 1
    }, {
        name: "帝江",
        prev: "御魄",
        isThree: 1
    }, {
        name: "混沌",
        prev: "御魄",
        isThree: 1
    }, {
        name: "魔巫",
        min: 13,
        prev: "魔灵"
    }, {
        name: "巫祝",
        min: 20,
        prev: "魔巫",
        ms: 1
    }, {
        name: "寒星",
        min: 20,
        prev: "魔巫",
        ms: 1
    }, {
        name: "狂魔",
        min: 20,
        prev: "魔巫",
        ms: 1
    }, {
        name: "兽灵",
        prev: "巫祝"
    }, {
        name: "地藏",
        prev: "巫祝"
    }, {
        name: "神火",
        prev: "寒星"
    }, {
        name: "飞羽",
        prev: "寒星"
    }, {
        name: "玄冥",
        prev: "狂魔"
    }, {
        name: "影舞",
        prev: "狂魔"
    }];